/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.crs.view.dashBoard;

import edu.ijse.crs.controller.UserController;
import edu.ijse.crs.dto.UserDTO;
import edu.ijse.crs.view.management.AdminManagementView;
import edu.ijse.crs.view.management.CourseManagementView;
import edu.ijse.crs.view.management.FacultyManagementView;
import edu.ijse.crs.view.report.GenerateReportsView;
import edu.ijse.crs.view.LoginView;
import edu.ijse.crs.view.management.StudentManagementView;
import edu.ijse.crs.view.UserUpdateView;
import java.awt.event.KeyEvent;

/**
 *
 * @author USER
 */
public class AdminDashBoardView extends DashBoardView {

    private UserController userController = new UserController();
    private LoginView loginView = new LoginView();

    /**
     * Creates new form DashBoardView
     */
    public AdminDashBoardView(UserDTO userDTO) {
        initComponents();
        setWelcomeText(userDTO);
        setTitle("Course Management System- Admin DashBoard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btsManageCourses = new javax.swing.JButton();
        lblWelcomeDashBoard = new javax.swing.JLabel();
        btnManageStudent = new javax.swing.JButton();
        btnManageFaculty = new javax.swing.JButton();
        btnManageAdmin = new javax.swing.JButton();
        btnManageUsers = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnGenerateReports = new javax.swing.JButton();
        lblWelcomeDash = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(255, 255, 102));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(85, 136, 201));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DashBoard");

        btsManageCourses.setBackground(new java.awt.Color(197, 225, 225));
        btsManageCourses.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        btsManageCourses.setText("Manage Courses");
        btsManageCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btsManageCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsManageCoursesActionPerformed(evt);
            }
        });
        btsManageCourses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btsManageCoursesKeyPressed(evt);
            }
        });

        lblWelcomeDashBoard.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblWelcomeDashBoard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnManageStudent.setBackground(new java.awt.Color(197, 225, 225));
        btnManageStudent.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        btnManageStudent.setText("Manage Students");
        btnManageStudent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentActionPerformed(evt);
            }
        });
        btnManageStudent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnManageStudentKeyPressed(evt);
            }
        });

        btnManageFaculty.setBackground(new java.awt.Color(197, 225, 225));
        btnManageFaculty.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        btnManageFaculty.setText("Manage Faculties");
        btnManageFaculty.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFacultyActionPerformed(evt);
            }
        });
        btnManageFaculty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnManageFacultyKeyPressed(evt);
            }
        });

        btnManageAdmin.setBackground(new java.awt.Color(197, 225, 225));
        btnManageAdmin.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        btnManageAdmin.setText("Manage Admins");
        btnManageAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAdminActionPerformed(evt);
            }
        });
        btnManageAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnManageAdminKeyPressed(evt);
            }
        });

        btnManageUsers.setBackground(new java.awt.Color(197, 225, 225));
        btnManageUsers.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        btnManageUsers.setText("Manage Users");
        btnManageUsers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUsersActionPerformed(evt);
            }
        });
        btnManageUsers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnManageUsersKeyPressed(evt);
            }
        });

        btnLogOut.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(85, 136, 201));
        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        btnLogOut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLogOutKeyPressed(evt);
            }
        });

        btnGenerateReports.setBackground(new java.awt.Color(197, 225, 225));
        btnGenerateReports.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        btnGenerateReports.setText("Generate Reports");
        btnGenerateReports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGenerateReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportsActionPerformed(evt);
            }
        });
        btnGenerateReports.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGenerateReportsKeyPressed(evt);
            }
        });

        lblWelcomeDash.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        lblWelcomeDash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeDash.setText("  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnManageStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnManageFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnManageAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btsManageCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnManageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGenerateReports, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblWelcomeDash, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWelcomeDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(btnLogOut)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lblWelcomeDashBoard))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWelcomeDash)
                        .addGap(29, 29, 29)
                        .addComponent(btnManageStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btsManageCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnManageAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnManageFaculty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnManageUsers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenerateReports)))
                .addGap(18, 18, 18)
                .addComponent(btnLogOut)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentActionPerformed
        manageStudent();
    }//GEN-LAST:event_btnManageStudentActionPerformed

    private void btsManageCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsManageCoursesActionPerformed
        manageCourse();
    }//GEN-LAST:event_btsManageCoursesActionPerformed

    private void btnManageFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFacultyActionPerformed
        manageFaculty();
    }//GEN-LAST:event_btnManageFacultyActionPerformed

    private void btnManageAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAdminActionPerformed
        manageAdmin();
    }//GEN-LAST:event_btnManageAdminActionPerformed

    private void btnManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUsersActionPerformed
        manageUser();
    }//GEN-LAST:event_btnManageUsersActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        logout();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnManageStudentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnManageStudentKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            manageStudent(); 
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btsManageCourses.requestFocus(); 
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            btnLogOut.requestFocus(); 
        }
    }//GEN-LAST:event_btnManageStudentKeyPressed

    private void btsManageCoursesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btsManageCoursesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            manageCourse(); 
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btnManageAdmin.requestFocus(); 
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            btnManageStudent.requestFocus(); 
        }
    }//GEN-LAST:event_btsManageCoursesKeyPressed

    private void btnManageAdminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnManageAdminKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            manageAdmin(); 
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btnManageFaculty.requestFocus(); 
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            btsManageCourses.requestFocus();
        }
    }//GEN-LAST:event_btnManageAdminKeyPressed

    private void btnManageFacultyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnManageFacultyKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            manageFaculty(); 
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btnManageUsers.requestFocus(); 
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            btnManageAdmin.requestFocus();
        }
    }//GEN-LAST:event_btnManageFacultyKeyPressed

    private void btnManageUsersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnManageUsersKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            manageUser(); 
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btnGenerateReports.requestFocus(); 
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            btnManageFaculty.requestFocus();
        }
    }//GEN-LAST:event_btnManageUsersKeyPressed

    private void btnLogOutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLogOutKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            logout(); 
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btnManageStudent.requestFocus(); 
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            btnGenerateReports.requestFocus();
        }
    }//GEN-LAST:event_btnLogOutKeyPressed

    private void btnGenerateReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportsActionPerformed
        generateReports();
    }//GEN-LAST:event_btnGenerateReportsActionPerformed

    private void btnGenerateReportsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGenerateReportsKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            generateReports(); 
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btnLogOut.requestFocus(); 
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            btnManageUsers.requestFocus();
        }
    }//GEN-LAST:event_btnGenerateReportsKeyPressed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateReports;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManageAdmin;
    private javax.swing.JButton btnManageFaculty;
    private javax.swing.JButton btnManageStudent;
    private javax.swing.JButton btnManageUsers;
    private javax.swing.JButton btsManageCourses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblWelcomeDash;
    private javax.swing.JLabel lblWelcomeDashBoard;
    // End of variables declaration//GEN-END:variables

    private void manageStudent() {
        new StudentManagementView(this).setVisible(true);
        this.setVisible(false);

    }

    private void manageCourse() {
        new CourseManagementView(this).setVisible(true);
        this.setVisible(false);
    }

    private void setWelcomeText(UserDTO userDTO) {
        if (userDTO != null) {
            lblWelcomeDash.setText("Welcome, " + userDTO.getUserName());
        }
    }

    private void manageAdmin() {
        new AdminManagementView(this).setVisible(true);
        this.setVisible(false);
    }

    private void manageFaculty() {
        new FacultyManagementView(this).setVisible(true);
        this.setVisible(false);
    }

    private void generateReports() {
        new GenerateReportsView(this).setVisible(true);
        this.setVisible(false);
    }

    private void logout() {
        new LoginView(this).setVisible(true);
        this.setVisible(false);
    }

    private void manageUser() {
        new UserUpdateView(this).setVisible(true);
        this.setVisible(false);
    }

}
