/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.crs.view.dashBoard;

import edu.ijse.crs.view.dashBoard.DashBoardView;
import edu.ijse.crs.controller.UserController;
import edu.ijse.crs.dto.UserDTO;
import edu.ijse.crs.view.management.EnrollmentManagementView;
import edu.ijse.crs.view.LoginView;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class StudentDashBoardView extends DashBoardView {

    private UserController userController = new UserController();
    private LoginView loginView = new LoginView();
    private UserDTO loggedInUser;

    /**
     * Creates new form DashBoardView
     */
    public StudentDashBoardView(UserDTO userDTO) {
        this.loggedInUser=userDTO;
        initComponents();
        setWelcomeText(userDTO);
        setTitle("Course Management System- Student DashBoard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblWelcomeDashBoard = new javax.swing.JLabel();
        btnManageEnrollment = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(85, 136, 201));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("DashBoard");

        lblWelcomeDashBoard.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblWelcomeDashBoard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnManageEnrollment.setBackground(new java.awt.Color(197, 225, 225));
        btnManageEnrollment.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        btnManageEnrollment.setText("Manage Enrollments");
        btnManageEnrollment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnrollmentActionPerformed(evt);
            }
        });
        btnManageEnrollment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnManageEnrollmentKeyPressed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(85, 136, 201));
        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        btnLogout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLogoutKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(lblWelcomeDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnManageEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(btnLogout)))
                .addContainerGap(191, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblHeader)
                .addGap(259, 259, 259))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWelcomeDashBoard)
                .addGap(72, 72, 72)
                .addComponent(btnManageEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnrollmentActionPerformed
        manageEnrollments();
    }//GEN-LAST:event_btnManageEnrollmentActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
       logout();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManageEnrollmentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnManageEnrollmentKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            manageEnrollments();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btnLogout.requestFocus(); 
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            btnLogout.requestFocus();
        }
    }//GEN-LAST:event_btnManageEnrollmentKeyPressed

    private void btnLogoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLogoutKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            logout();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btnManageEnrollment.requestFocus(); 
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            btnManageEnrollment.requestFocus();
        }
    }//GEN-LAST:event_btnLogoutKeyPressed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageEnrollment;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblWelcomeDashBoard;
    // End of variables declaration//GEN-END:variables


    private void setWelcomeText(UserDTO userDTO) {
        if (userDTO != null) {
            lblWelcomeDashBoard.setText("Welcome, " + userDTO.getUserName());
        }
    }



    private void manageEnrollments() {
        
        EnrollmentManagementView view = new EnrollmentManagementView(this,loggedInUser);
        view.setVisible(true);
        this.setVisible(false);
    }

    private void logout() {
        new LoginView(this).setVisible(true);
        this.setVisible(false);
    }
}
