/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.crs.view.report;

import edu.ijse.crs.view.report.SelectStudentView;
import edu.ijse.crs.view.report.SelectCourseView;
import edu.ijse.crs.view.dashBoard.DashBoardView;

/**
 *
 * @author USER
 */
public class GenerateReportsView extends javax.swing.JFrame {

    private DashBoardView dashBoardView;

    /**
     * Creates new form GenerateReportsView
     */
    public GenerateReportsView(DashBoardView dashBoardView) {
        this.dashBoardView = dashBoardView;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStudent = new javax.swing.JButton();
        btnHeader = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnCourse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStudent.setBackground(new java.awt.Color(197, 225, 225));
        btnStudent.setFont(new java.awt.Font("Segoe UI Historic", 1, 30)); // NOI18N
        btnStudent.setForeground(new java.awt.Color(85, 136, 201));
        btnStudent.setText("Students");
        btnStudent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });

        btnHeader.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnHeader.setForeground(new java.awt.Color(85, 136, 201));
        btnHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHeader.setText("Generate Reports");

        btnBack.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(85, 136, 201));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCourse.setBackground(new java.awt.Color(197, 225, 225));
        btnCourse.setFont(new java.awt.Font("Segoe UI Historic", 1, 30)); // NOI18N
        btnCourse.setForeground(new java.awt.Color(85, 136, 201));
        btnCourse.setText("Courses");
        btnCourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(274, 274, 274))))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(btnHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(btnHeader)
                .addGap(42, 42, 42)
                .addComponent(btnStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCourse)
                .addGap(24, 24, 24)
                .addComponent(btnBack)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        selectStudent();
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        back();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseActionPerformed
        selectCourse();
    }//GEN-LAST:event_btnCourseActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCourse;
    private javax.swing.JLabel btnHeader;
    private javax.swing.JButton btnStudent;
    // End of variables declaration//GEN-END:variables

    private void selectStudent() {
        new SelectStudentView(this).setVisible(true);
        this.setVisible(false);
    }

    private void selectCourse() {
        new SelectCourseView(this).setVisible(true);
        this.setVisible(false);
    }

    private void back() {
        this.setVisible(false);
        dashBoardView.setVisible(true);
    }
}
