/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.crs.view.report;

import edu.ijse.crs.view.report.CourseReportView;
import edu.ijse.crs.controller.CourseController;
import edu.ijse.crs.dto.CourseDTO;
import edu.ijse.crs.dto.StudentDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class SelectCourseView extends javax.swing.JFrame {

    private GenerateReportsView generateReportsView;
    private CourseController courseController = new CourseController();

    /**
     * Creates new form SelectStudentView
     */
    public SelectCourseView(GenerateReportsView generateReportsView) {
        this.generateReportsView = generateReportsView;
        initComponents();

        try {
            populateComboSelectCourse(); // Load courses safely
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to load courses: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboSelectCourse = new javax.swing.JComboBox<>();
        lblSelectCourse = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboSelectCourse.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        comboSelectCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboSelectCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSelectCourseActionPerformed(evt);
            }
        });

        lblSelectCourse.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblSelectCourse.setForeground(new java.awt.Color(85, 136, 201));
        lblSelectCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectCourse.setText("Select Course");

        btnConfirm.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(85, 136, 201));
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(85, 136, 201));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(btnConfirm))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSelectCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(comboSelectCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lblSelectCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboSelectCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed

        confirm();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void comboSelectCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSelectCourseActionPerformed

    }//GEN-LAST:event_comboSelectCourseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        back();
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> comboSelectCourse;
    private javax.swing.JLabel lblSelectCourse;
    // End of variables declaration//GEN-END:variables

    private void back() {
        this.setVisible(false);
        generateReportsView.setVisible(true);
    }

    private void populateComboSelectCourse() {
        try {
            comboSelectCourse.removeAllItems();
            ArrayList<CourseDTO> courses = courseController.getAllCourses();
            for (CourseDTO course : courses) {
                comboSelectCourse.addItem(course.getTitle());
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "An error occurred while populating the comboBox " + e.getMessage());
        }

    }

    public String getSelectedCourse() {
        return comboSelectCourse.getSelectedItem().toString();
    }

    private void generateReportForSelectedCourse() {
        String selectedCourse = getSelectedCourse();

        if (selectedCourse != null && !selectedCourse.trim().isEmpty()) {
            CourseReportView reportView = new CourseReportView(this);
            reportView.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a course before generating the report.");
        }
    }

    private void confirm() {
        generateReportForSelectedCourse();
    }
}
